version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  install:
    executor: 
      name: node/default
      tag: 14.16.0
    steps:
      - node/install-packages
workflows:
  test:
    when:
      not:
        equal: [master, <<pipeline.git.branch>>]
    jobs:
      - install
