version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  install:
    executor: 
      name: node/default
      tag: 14.16.0
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
  test: 
    executor: 
      name: node/default
      tag: 14.16.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: "Running unit tests"
          command: npm run test
          working_directory: ~/project
workflows:
  test:
    when:
      not:
        equal: [master, <<pipeline.git.branch>>]
    jobs:
      - install
      - test:
          requires: 
            - install

